// Base temps of crops
export const baseTemps = {
  corn: 50, // Base GDD 50°F
  soybean: 50, // Base GDD 50°F
  wheat: 40, // Base GDD 40°F
  alfalfa: 41, // Base GDD 41°F
  cotton: 60, // Base GDD 60°F
  tomato: 50, // Base GDD 50°F
  lettuce: 40, // Base GDD 40°F
  cucumber: 55, // Base GDD 55°F
  rice: 50, // Base GDD 50°F
  potato: 45, // Base GDD 45°F
};

// Emergence GDD of crops
export const emergenceGDD = {
  corn: 90, // Approx. 90 GDDs for corn to emerge
  soybean: 120, // Approx. 120 GDDs for soybean
  wheat: 180, // Approx. 180 GDDs for wheat
  alfalfa: 200, // Approx. 200 GDDs for alfalfa
  cotton: 200, // Approx. 200 GDDs for cotton
  tomato: 150, // Approx. 150 GDDs for tomato
  lettuce: 120, // Approx. 120 GDDs for lettuce
  cucumber: 150, // Approx. 150 GDDs for cucumber
  rice: 100, // Approx. 100 GDDs for rice
  potato: 120, // Approx. 120 GDDs for potato
};

export const pestData = [
  {
    pest: "American plum borer",
    lifeStage: "adult flight and egg laying",
    gddRange: { minGdd: 245, maxGdd: 440 },
    degreeDayMaps: [250, 300, 450],
    reference: "1",
  },
  {
    pest: "American plum borer",
    lifeStage: "2nd generation",
    gddRange: { minGdd: 1375, maxGdd: 1500 },
    degreeDayMaps: [1350, 1400, 1500],
    reference: "1",
  },
  {
    pest: "Arborvitae leafminer",
    lifeStage: "larvae in mines; 1st generation",
    gddRange: { minGdd: 245, maxGdd: 360 },
    degreeDayMaps: [250, 300, 350],
    reference: "1",
  },
  {
    pest: "Arborvitae leafminer",
    lifeStage: "2nd generation",
    gddRange: { minGdd: 533, maxGdd: 700 },
    degreeDayMaps: [500, 600, 700],
    reference: "1",
  },
  {
    pest: "Arborvitae leafminer",
    lifeStage: "3rd generation",
    gddRange: { minGdd: 1700, maxGdd: 2100 },
    degreeDayMaps: [1700, 1900, 2000],
    reference: "1",
  },
  {
    pest: "Balsam gall midge",
    lifeStage: "adults laying eggs",
    gddRange: { minGdd: 150, maxGdd: 300 },
    degreeDayMaps: [150, 200, 300],
    reference: "3",
  },
  {
    pest: "Balsam gall midge",
    lifeStage: "galls apparent",
    gddRange: { minGdd: 550, maxGdd: 700 },
    degreeDayMaps: [550, 650, 700],
    reference: "3",
  },
  {
    pest: "Balsam twig aphid",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 60, maxGdd: 100 },
    degreeDayMaps: [50, 100],
    reference: "4",
  },
  {
    pest: "Balsam twig aphid",
    lifeStage: "stem mothers present (control target)",
    gddRange: { minGdd: 100, maxGdd: 140 },
    degreeDayMaps: [100, 150],
    reference: "4",
  },
  {
    pest: "Banded ash clearwing borer",
    lifeStage: "adult emergence",
    gddRange: { minGdd: 1800, maxGdd: 2200 },
    degreeDayMaps: [1800, 1900, 2000],
    reference: "1,2",
  },
  {
    pest: "Beech scale",
    lifeStage: "eggs present",
    gddRange: { minGdd: 800, maxGdd: 800 },
    degreeDayMaps: [800],
    reference: "3",
  },
  {
    pest: "Beech scale",
    lifeStage: "egg hatch; 1st crawlers",
    gddRange: { minGdd: 1250, maxGdd: 1250 },
    degreeDayMaps: [1250],
    reference: "3",
  },
  {
    pest: "Birch leafminer",
    lifeStage: "1st adult emergence",
    gddRange: { minGdd: 175, maxGdd: 215 },
    degreeDayMaps: [150, 200],
    reference: "1",
  },
  {
    pest: "Birch leafminer",
    lifeStage: "Adults laying eggs",
    gddRange: { minGdd: 275, maxGdd: 375 },
    degreeDayMaps: [250, 300, 350],
    reference: "2",
  },
  {
    pest: "Birch leafminer",
    lifeStage: "larvae and pupae",
    gddRange: { minGdd: 375, maxGdd: 500 },
    degreeDayMaps: [350, 400, 500],
    reference: "2",
  },
  {
    pest: "Birch leafminer",
    lifeStage: "adults and egg laying; 2nd generation",
    gddRange: { minGdd: 600, maxGdd: 700 },
    degreeDayMaps: [600, 700],
    reference: "2",
  },
  {
    pest: "Black pineleaf scale",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 1068, maxGdd: 1068 },
    degreeDayMaps: [1050],
    reference: "1",
  },
  {
    pest: "Bronze birch borer",
    lifeStage: "adults; eggs; new grubs",
    gddRange: { minGdd: 400, maxGdd: 600 },
    degreeDayMaps: [400, 500, 600],
    reference: "1,2",
  },
  {
    pest: "Cankerworm",
    lifeStage: "young caterpillars",
    gddRange: { minGdd: 100, maxGdd: 200 },
    degreeDayMaps: [100, 200],
    reference: "1",
  },
  {
    pest: "Cooley spruce gall adelgid",
    lifeStage: "1st adults active - Spruce (control target)",
    gddRange: { minGdd: 25, maxGdd: 120 },
    degreeDayMaps: [50, 100],
    reference: "3",
  },
  {
    pest: "Cooley spruce gall adelgid",
    lifeStage: "1st galls visible - Spruce",
    gddRange: { minGdd: 200, maxGdd: 310 },
    degreeDayMaps: [200, 250, 300],
    reference: "3",
  },
  {
    pest: "Cooley spruce gall adelgid",
    lifeStage: "1st adults active - Douglas fir",
    gddRange: { minGdd: 90, maxGdd: 180 },
    degreeDayMaps: [100, 150],
    reference: "1",
  },
  {
    pest: "Cooley spruce gall adelgid",
    lifeStage: "1st nymphs - Douglas fir (control target)",
    gddRange: { minGdd: 90, maxGdd: 150 },
    degreeDayMaps: [100, 150],
    reference: "3",
  },
  {
    pest: "Cooley spruce gall adelgid",
    lifeStage: "2nd nymphs - Douglas fir (control target)",
    gddRange: { minGdd: 600, maxGdd: 1000 },
    degreeDayMaps: [600, 800, 1000],
    reference: "3",
  },
  {
    pest: "Cooley spruce gall adelgid",
    lifeStage: "2nd adults active (control target)",
    gddRange: { minGdd: 1500, maxGdd: 1600 },
    degreeDayMaps: [1500, 1550, 1600],
    reference: "3",
  },
  {
    pest: "Cottony maple scale",
    lifeStage: "adults & yellow crawlers on leaf veins",
    gddRange: { minGdd: 802, maxGdd: 1200 },
    degreeDayMaps: [800, 950, 1200],
    reference: "1,2",
  },
  {
    pest: "Dogwood borer",
    lifeStage: "adults, eggs, caterpillars",
    gddRange: { minGdd: 350, maxGdd: 850 },
    degreeDayMaps: [350, 550, 850],
    reference: "1,2",
  },
  {
    pest: "Eastern pine shoot borer",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 75, maxGdd: 200 },
    degreeDayMaps: [50, 100, 200],
    reference: "3",
  },
  {
    pest: "Eastern spruce gall adelgid",
    lifeStage: "1st adults active (control target)",
    gddRange: { minGdd: 25, maxGdd: 100 },
    degreeDayMaps: [50, 100],
    reference: "3",
  },
  {
    pest: "Eastern spruce gall adelgid",
    lifeStage: "egg hatch, galls begin forming",
    gddRange: { minGdd: 250, maxGdd: 310 },
    degreeDayMaps: [250, 300],
    reference: "1,3",
  },
  {
    pest: "Eastern spruce gall adelgid",
    lifeStage: "2nd adults active (control target)",
    gddRange: { minGdd: 1500, maxGdd: 1600 },
    degreeDayMaps: [1500, 1550, 1600],
    reference: "3",
  },
  {
    pest: "Eastern tent caterpillar",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 45, maxGdd: 100 },
    degreeDayMaps: [50, 100],
    reference: "1,2,3",
  },
  {
    pest: "Eastern tent caterpillar",
    lifeStage: "tents apparent",
    gddRange: { minGdd: 150, maxGdd: 150 },
    degreeDayMaps: [150],
    reference: "3",
  },
  {
    pest: "Eastern tent caterpillar",
    lifeStage: "pupation",
    gddRange: { minGdd: 450, maxGdd: 450 },
    degreeDayMaps: [450],
    reference: "3",
  },
  {
    pest: "Elm leaf beetle",
    lifeStage: "1st generation",
    gddRange: { minGdd: 400, maxGdd: 600 },
    degreeDayMaps: [400, 500, 600],
    reference: "1",
  },
  {
    pest: "Elm leaf beetle",
    lifeStage: "2nd generation",
    gddRange: { minGdd: 1300, maxGdd: 1300 },
    degreeDayMaps: [1300],
    reference: "1",
  },
  {
    pest: "Elm leafminer",
    lifeStage: "adult emergence",
    gddRange: { minGdd: 215, maxGdd: 240 },
    degreeDayMaps: [200, 250],
    reference: "1",
  },
  {
    pest: "Elm leafminer",
    lifeStage: "1st generation larvae",
    gddRange: { minGdd: 365, maxGdd: 530 },
    degreeDayMaps: [350, 450, 550],
    reference: "2",
  },
  {
    pest: "Emerald ash borer",
    lifeStage: "1st adult emergence",
    gddRange: { minGdd: 400, maxGdd: 500 },
    degreeDayMaps: [400, 500],
    reference: "3",
  },
  {
    pest: "Emerald ash borer",
    lifeStage: "peak adult activity",
    gddRange: { minGdd: 1000, maxGdd: 1200 },
    degreeDayMaps: [1000, 1100, 1200],
    reference: "*",
  },
  {
    pest: "Euonymus scale",
    lifeStage: "egg hatch - 1st generation",
    gddRange: { minGdd: 400, maxGdd: 575 },
    degreeDayMaps: [400, 500, 550],
    reference: "1",
  },
  {
    pest: "Euonymus scale",
    lifeStage: "egg hatch - 2nd generation",
    gddRange: { minGdd: 1900, maxGdd: 1050 },
    degreeDayMaps: [],
    reference: "1",
  },
  {
    pest: "European pine sawfly",
    lifeStage: "1st larvae",
    gddRange: { minGdd: 100, maxGdd: 195 },
    degreeDayMaps: [100, 150, 200],
    reference: "1,3",
  },
  {
    pest: "European pine shoot moth",
    lifeStage: "1st larvae",
    gddRange: { minGdd: 50, maxGdd: 220 },
    degreeDayMaps: [50, 100, 200],
    reference: "3",
  },
  {
    pest: "European pine shoot moth",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 900, maxGdd: 1000 },
    degreeDayMaps: [900, 950, 1000],
    reference: "3",
  },
  {
    pest: "European pine shoot moth",
    lifeStage: "adults active",
    gddRange: { minGdd: 700, maxGdd: 800 },
    degreeDayMaps: [700, 750, 800],
    reference: "3",
  },
  {
    pest: "Fall webworm",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 850, maxGdd: 900 },
    degreeDayMaps: [850, 900],
    reference: "1",
  },
  {
    pest: "Fall webworm",
    lifeStage: "caterpillars feeding",
    gddRange: { minGdd: 1200, maxGdd: 1800 },
    degreeDayMaps: [1200, 1500, 1800],
    reference: "2",
  },
  {
    pest: "Fall webworm",
    lifeStage: "tents become apparent",
    gddRange: { minGdd: 1850, maxGdd: 2050 },
    degreeDayMaps: [1850, 1900, 2000],
    reference: "3",
  },
  {
    pest: "Fletcher scale",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 850, maxGdd: 900 },
    degreeDayMaps: [850, 900],
    reference: "1",
  },
  {
    pest: "Forest tent caterpillar",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 125, maxGdd: 250 },
    degreeDayMaps: [100, 150, 250],
    reference: "3",
  },
  {
    pest: "Forest tent caterpillar",
    lifeStage: "pupation",
    gddRange: { minGdd: 450, maxGdd: 450 },
    degreeDayMaps: [450],
    reference: "3",
  },
  {
    pest: "Forest tent caterpillar",
    lifeStage: "tachinid parasitic flies abundant",
    gddRange: { minGdd: 450, maxGdd: 550 },
    degreeDayMaps: [450, 500, 550],
    reference: "3",
  },
  {
    pest: "Forest tent caterpillar",
    lifeStage:
      'sarcophagid parasitic flies abundant ("government fly" or "friendly fly")',
    gddRange: { minGdd: 750, maxGdd: 850 },
    degreeDayMaps: [750, 800, 850],
    reference: "*",
  },
  {
    pest: "Golden oak scale",
    lifeStage: "Egg hatch",
    gddRange: { minGdd: 680, maxGdd: 700 },
    degreeDayMaps: [650, 700],
    reference: "1",
  },
  {
    pest: "Greater peach tree borer",
    lifeStage: "adult emergence",
    gddRange: { minGdd: 575, maxGdd: 710 },
    degreeDayMaps: [550, 650, 700],
    reference: "1",
  },
  {
    pest: "Gypsy moth",
    lifeStage: "egg hatch, 1st larvae",
    gddRange: { minGdd: 145, maxGdd: 200 },
    degreeDayMaps: [150, 200],
    reference: "1, 3",
  },
  {
    pest: "Gypsy moth",
    lifeStage: "young caterpillars",
    gddRange: { minGdd: 450, maxGdd: 450 },
    degreeDayMaps: [450],
    reference: "1",
  },
  {
    pest: "Gypsy moth",
    lifeStage: "pupation",
    gddRange: { minGdd: 900, maxGdd: 1200 },
    degreeDayMaps: [900, 1000, 1200],
    reference: "3",
  },
  {
    pest: "Honeylocust spider mite",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 220, maxGdd: 250 },
    degreeDayMaps: [200, 250],
    reference: "1",
  },
  {
    pest: "Honeylocust plant bug",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 220, maxGdd: 250 },
    degreeDayMaps: [200, 250],
    reference: "1,3",
  },
  {
    pest: "Introduced pine sawfly",
    lifeStage: "1st larvae",
    gddRange: { minGdd: 400, maxGdd: 600 },
    degreeDayMaps: [400, 500, 600],
    reference: "3",
  },
  {
    pest: "Imported willow leaf beetle",
    lifeStage: "Adults active",
    gddRange: { minGdd: 120, maxGdd: 275 },
    degreeDayMaps: [150, 250, 300],
    reference: "1",
  },
  {
    pest: "Jack pine budworm",
    lifeStage: "young larvae feeding",
    gddRange: { minGdd: 300, maxGdd: 350 },
    degreeDayMaps: [300, 350],
    reference: "3",
  },
  {
    pest: "Jack pine budworm",
    lifeStage: "large larvae feeding - defoliation apparent",
    gddRange: { minGdd: 650, maxGdd: 700 },
    degreeDayMaps: [650, 700],
    reference: "3",
  },
  {
    pest: "Jack pine sawfly",
    lifeStage: "eggs; young larvae",
    gddRange: { minGdd: 100, maxGdd: 200 },
    degreeDayMaps: [100, 150, 200],
    reference: "1",
  },
  {
    pest: "Jack pine sawfly",
    lifeStage: "larger larvae consuming needles",
    gddRange: { minGdd: 275, maxGdd: 500 },
    degreeDayMaps: [250, 350, 500],
    reference: "1",
  },
  {
    pest: "Japanese beetle",
    lifeStage: "adults emerge and feed",
    gddRange: { minGdd: 950, maxGdd: 2150 },
    degreeDayMaps: [950, 1500, 2000],
    reference: "1,2",
  },
  {
    pest: "Juniper scale",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 550, maxGdd: 700 },
    degreeDayMaps: [550, 600, 700],
    reference: "1",
  },
  {
    pest: "Larch casebearer",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 120, maxGdd: 150 },
    degreeDayMaps: [100, 150],
    reference: "1",
  },
  {
    pest: "Large aspen tortrix",
    lifeStage: "pupation",
    gddRange: { minGdd: 600, maxGdd: 700 },
    degreeDayMaps: [600, 700],
    reference: "3",
  },
  {
    pest: "Lesser peach tree borer",
    lifeStage: "adult flight",
    gddRange: { minGdd: 350, maxGdd: 375 },
    degreeDayMaps: [300, 350, 400],
    reference: "1,2",
  },
  {
    pest: "Lilac borer",
    lifeStage: "adult flight",
    gddRange: { minGdd: 325, maxGdd: 350 },
    degreeDayMaps: [300, 350],
    reference: "1,2",
  },
  {
    pest: "Magnolia scale",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 1925, maxGdd: 1950 },
    degreeDayMaps: [1900, 2000],
    reference: "1",
  },
  {
    pest: "Mimosa webworm",
    lifeStage: "egg hatch - 1st generation",
    gddRange: { minGdd: 850, maxGdd: 900 },
    degreeDayMaps: [850, 900],
    reference: "1",
  },
  {
    pest: "Northern pine weevil",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 25, maxGdd: 100 },
    degreeDayMaps: [50, 100],
    reference: "3",
  },
  {
    pest: "Northern pine weevil",
    lifeStage: "2nd adults active",
    gddRange: { minGdd: 1200, maxGdd: 1400 },
    degreeDayMaps: [1200, 1300, 1400],
    reference: "3",
  },
  {
    pest: "Oystershell scale",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 350, maxGdd: 500 },
    degreeDayMaps: [350, 400, 500],
    reference: "1",
  },
  {
    pest: "Pales weevil",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 25, maxGdd: 100 },
    degreeDayMaps: [50, 100],
    reference: "3",
  },
  {
    pest: "Pales weevil",
    lifeStage: "2nd adults active",
    gddRange: { minGdd: 1200, maxGdd: 1400 },
    degreeDayMaps: [1200, 1300, 1400],
    reference: "3",
  },
  {
    pest: "Pine chafer (Anomela beetle)",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 450, maxGdd: 600 },
    degreeDayMaps: [450, 500, 600],
    reference: "3",
  },
  {
    pest: "Pine engraver (Ips bark beetle)",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 100, maxGdd: 150 },
    degreeDayMaps: [100, 150],
    reference: "100, 150",
  },
  {
    pest: "Pine needle midge",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 400, maxGdd: 500 },
    degreeDayMaps: [400, 450, 500],
    reference: "3",
  },
  {
    pest: "Pine needle scale",
    lifeStage: "1st generation egg hatch",
    gddRange: { minGdd: 250, maxGdd: 400 },
    degreeDayMaps: [250, 300, 400],
    reference: "1,3,5,7",
  },
  {
    pest: "Pine needle scale",
    lifeStage: "1st generation - hyaline stage (control target)",
    gddRange: { minGdd: 400, maxGdd: 500 },
    degreeDayMaps: [400, 500],
    reference: "5",
  },
  {
    pest: "Pine needle scale",
    lifeStage: "2nd generation egg hatch",
    gddRange: { minGdd: 1250, maxGdd: 1350 },
    degreeDayMaps: [1250, 1300, 1350],
    reference: "1,3,5",
  },
  {
    pest: "Pine needle scale",
    lifeStage: "2nd generation - hyaline stage (control target)",
    gddRange: { minGdd: 1500, maxGdd: 1500 },
    degreeDayMaps: [1500],
    reference: "5",
  },
  {
    pest: "Pine root collar weevil",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 300, maxGdd: 350 },
    degreeDayMaps: [300, 350],
    reference: "3",
  },
  {
    pest: "Pine root collar weevil",
    lifeStage: "2nd adults active",
    gddRange: { minGdd: 1200, maxGdd: 1400 },
    degreeDayMaps: [1200, 1300, 1400],
    reference: "3",
  },
  {
    pest: "Pine shoot beetle",
    lifeStage: "new adults emerge; begin shoot-feeding",
    gddRange: { minGdd: 500, maxGdd: 550 },
    degreeDayMaps: [500, 550],
    reference: "6",
  },
  {
    pest: "Pine shoot beetle",
    lifeStage: "optimal control window",
    gddRange: { minGdd: 450, maxGdd: 500 },
    degreeDayMaps: [450, 500],
    reference: "6",
  },
  {
    pest: "Pine tortoise scale",
    lifeStage: "egg hatch begins; 1st crawlers",
    gddRange: { minGdd: 400, maxGdd: 500 },
    degreeDayMaps: [400, 450, 500],
    reference: "3",
  },
  {
    pest: "Pine tortoise scale",
    lifeStage: "egg hatch ends; last of the crawlers",
    gddRange: { minGdd: 1000, maxGdd: 1200 },
    degreeDayMaps: [1000, 1100, 1200],
    reference: "3",
  },
  {
    pest: "Pine tube moth",
    lifeStage: "adults; egg laying; caterpillars",
    gddRange: { minGdd: 90, maxGdd: 250 },
    degreeDayMaps: [100, 200, 250],
    reference: "1",
  },
  {
    pest: "Red-headed pine sawfly",
    lifeStage: "1st larvae",
    gddRange: { minGdd: 400, maxGdd: 600 },
    degreeDayMaps: [400, 500, 600],
    reference: "3",
  },
  {
    pest: "Spruce budscale",
    lifeStage: "egg hatch, 1st crawlers",
    gddRange: { minGdd: 700, maxGdd: 1150 },
    degreeDayMaps: [700, 900, 1150],
    reference: "1,3",
  },
  {
    pest: "Spruce budworm",
    lifeStage: "1st larvae",
    gddRange: { minGdd: 200, maxGdd: 300 },
    degreeDayMaps: [200, 250, 300],
    reference: "3",
  },
  {
    pest: "Spruce needleminer",
    lifeStage: "1st larvae",
    gddRange: { minGdd: 150, maxGdd: 200 },
    degreeDayMaps: [150, 200],
    reference: "3",
  },
  {
    pest: "Spruce spider mite",
    lifeStage: "1st egg hatch",
    gddRange: { minGdd: 150, maxGdd: 175 },
    degreeDayMaps: [150, 200],
    reference: "1,3",
  },
  {
    pest: "Striped pine scale",
    lifeStage: "egg hatch",
    gddRange: { minGdd: 750, maxGdd: 800 },
    degreeDayMaps: [750, 800],
    reference: "1",
  },
  {
    pest: "Turpentine beetle",
    lifeStage: "parent beetles colonizing brood material",
    gddRange: { minGdd: 300, maxGdd: 350 },
    degreeDayMaps: [300, 350],
    reference: "3",
  },
  {
    pest: "Walnut caterpillar",
    lifeStage: "egg hatch; caterpillars",
    gddRange: { minGdd: 1600, maxGdd: 1700 },
    degreeDayMaps: [1600, 1650, 1700],
    reference: "1",
  },
  {
    pest: "White pine weevil",
    lifeStage: "1st adults active",
    gddRange: { minGdd: 25, maxGdd: 220 },
    degreeDayMaps: [50, 100, 200],
    reference: "3",
  },
  {
    pest: "White pine weevil",
    lifeStage: "2nd adults active",
    gddRange: { minGdd: 1200, maxGdd: 1400 },
    degreeDayMaps: [1200, 1300, 1400],
    reference: "3",
  },
  {
    pest: "Zimmerman pine moth",
    lifeStage: "1st larvae",
    gddRange: { minGdd: 25, maxGdd: 100 },
    degreeDayMaps: [50, 100],
    reference: "7",
  },
  {
    pest: "Zimmerman pine moth",
    lifeStage: "adult flight",
    gddRange: { minGdd: 1700, maxGdd: 1700 },
    degreeDayMaps: [1700],
    reference: "1",
  },
];
